# This file allows you to configure the Dart analyzer.
#
# The commented part below is just for inspiration. Read the guide here:
#   https://www.dartlang.org/guides/language/analysis-options

 analyzer:
#   exclude:
#     - path/to/excluded/files/**
 linter:
   rules:
#     # see catalog here: http://dart-lang.github.io/linter/lints/
     - hash_and_equals
     - avoid_empty_else
     - cancel_subscriptions
##     - close_sinks
     - comment_references
     - control_flow_in_finally
     - empty_statements
     - hash_and_equals
     - invariant_booleans
     - iterable_contains_unrelated_type
     - list_remove_unrelated_type
     - literal_only_boolean_expressions
     - test_types_in_equals
     - throw_in_finally
     - unrelated_type_equality_checks
     - valid_regexps
     - always_declare_return_types
#     - always_specify_types
     - avoid_return_types_on_setters
     - await_only_futures
     - camel_case_types
     - constant_identifier_names
     - empty_catches
     - empty_constructor_bodies
     - implementation_imports
     - library_names
     - library_prefixes
     - non_constant_identifier_names
     - one_member_abstracts
     - only_throw_errors
     - overridden_fields
     - package_api_docs
     - package_prefixed_library_names
     - parameter_assignments
     - prefer_final_locals
     - prefer_is_not_empty
     - slash_for_doc_comments
     - sort_constructors_first
     - sort_unnamed_constructors_first
     - super_goes_last
     - type_annotate_public_apis
     - type_init_formals
#     - unnecessary_getters_setters
     - package_names