name: json_object_lite
description: Allow use of JSON Maps in dot notation format without using mirrors.
version: 2.1.1
homepage: https://github.com/shamblett/json_object_lite

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dev_dependencies:
  pana: '^0.14.4'
  test: '^1.16.0-nullsafety.16'
  build_runner: '^1.10.13'
  build_test: '^1.3.4'
  build_web_compilers: '^2.16.0'


