name: json_object_lite
description: Allow use of JSON Maps in dot notation format without using mirrors.
version: 4.0.0
homepage: https://github.com/shamblett/json_object_lite

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: '^1.24.2'
  build_runner: '^2.4.4'
  build_test: '^2.1.7'
  build_web_compilers: '^4.0.3'
  lints: '^2.1.0'

