name: json_object_lite
description: Allow use of JSON Maps in dot notation format without using mirrors.
version: 4.0.1
homepage: https://github.com/shamblett/json_object_lite

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: '^1.25.0'
  build_runner: '^2.4.7'
  build_test: '^2.2.2'
  build_web_compilers: '^4.0.7'
  lints: '^3.0.0'

