name: json_object_lite
description: Allow use of JSON Maps in dot notation format without using mirrors.
version: 3.0.1
homepage: https://github.com/shamblett/json_object_lite

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: '^1.21.5'
  build_runner: '^2.2.0'
  build_test: '^2.1.5'
  build_web_compilers: '^3.2.5'
  lints: '^2.0.0'

