name: json_object_lite
description: Allow use of JSON Maps in dot notation format without using mirrors.
version: 2.1.1
homepage: https://github.com/shamblett/json_object_lite

environment:
  sdk: '>=2.0.0-dev  <3.0.0'

dev_dependencies:
  test: '^1.6.5'
  dart_style: '^1.2.9'
  dartdoc: '^0.28.4'
  build_runner: '^1.6.2'
  build_test: '^0.10.8'
  build_web_compilers: '^2.1.4'
