name: json_object_lite
description: Allow use of JSON Maps in dot notation format without using mirrors.
version: 3.0.0
homepage: https://github.com/shamblett/json_object_lite

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pana: '^0.15.3'
  test: '^1.16.5'
  build_runner: '^1.11.1'
  build_test: '^1.3.6'
  build_web_compilers: '^2.16.3'


